var TEXT_PLAYER_COLOUR = "SELECT P{0} COLOUR";

var TEXT_HELP_1 = "REACH THE END OF THE BOARD LAUNCHING THE DICE. ROLLING A 6 WILL GIVE THE PLAYER AN EXTRA DICE";
var TEXT_HELP2_PT1 = "LADDER: YOU GO UP!";
var TEXT_HELP2_PT2 = ": YOU GO DOWN!";
var TEXT_MODE0 = "SNAKE";
var TEXT_MODE1 = "CHUTE";

var TEXT_EXTRA_DICE = "EXTRA DICE!";
var TEXT_SELECT_MODE = "SELECT GAME MODE";
var TEXT_SELECT_OPPONENTS = "SELECT OPPONENTS";
var TEXT_SELECT_PLAYERS = "SELECT PLAYERS";
var TEXT_SELECT_COLOUR = "SELECT YOUR COLOUR";
var TEXT_GAMES_PLAYED = "GAMES PLAYED";
var TEXT_GAMES_WON = "GAMES WON";
var TEXT_WIN = "YOU WON";
var TEXT_LOSE = "YOU LOSE";
var TEXT_PAUSE = "PAUSE";
var TEXT_ARE_SURE = "ARE YOU SURE?";

var TEXT_MOTIVATIONAL0 = "GREAT!";
var TEXT_MOTIVATIONAL1 = "COOL!";
var TEXT_MOTIVATIONAL2 = "NICE!";
var TEXT_MOTIVATIONAL3 = "SUPER!";
var TEXT_MOTIVATIONAL4 = "GOOD!";
var TEXT_DEMOTIVATIONAL0 = "BAD ROLL!";
var TEXT_DEMOTIVATIONAL1 = "NOOOO!";
var TEXT_DEMOTIVATIONAL2 = "SORRY...";
var TEXT_DEMOTIVATIONAL3 = "UNLUCKY!";
var TEXT_DEMOTIVATIONAL4 = "BAD RESULT!";

var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_CREDITS_DEVELOPED = "Developed by";
var TEXT_LINK = "www.codethislab.com";

var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT LOCAL STORAGE. IF YOU'RE USING SAFARI, IT MAY BE RELATED TO PRIVATE BROWSING. AS A RESULT, SOME INFO MAY NOT BE SAVED OR SOME FEATURES MAY NOT BE AVAILABLE.";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better?";